// client-side helper for printing and pdf generation
// Install: npm i jspdf jspdf-autotable
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/** sanitize filename */
const sanitizeFilename = (name = "Attendance") =>
  name.replace(/[\/\\?%*:|"<>]/g, "_");

/** build a simple header for jsPDF pages */
function drawPdfHeader(doc, pageWidth, margin, title, student) {
  const name = student?.name || "";
  const role = student?.role || "";

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(name, margin.left, 40);

  if (role) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(role, margin.left, 56);
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(title, pageWidth / 2, 48, { align: "center" });

  doc.setDrawColor(220);
  doc.setLineWidth(0.6);
  doc.line(margin.left, 64, pageWidth - margin.right, 64);
}

/** build footer for jsPDF pages */
function drawPdfFooter(doc, pageWidth, margin, pageNumber) {
  const pageCount = doc.internal.getNumberOfPages();
  const footerY = doc.internal.pageSize.getHeight() - 30;

  doc.setDrawColor(240);
  doc.setLineWidth(0.4);
  doc.line(margin.left, footerY - 8, pageWidth - margin.right, footerY - 8);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`Page ${pageNumber} of ${pageCount}`, pageWidth - margin.right, footerY, {
    align: "right",
  });

  doc.text("Generated by Desinerz Academy", margin.left, footerY);
}

/** download PDF of records */
export function downloadPDF(tableTitle = "Attendance", tableRecords = [], student = {}) {
  if (!tableRecords || tableRecords.length === 0) return;

  const doc = new jsPDF({
    unit: "pt",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = { top: 80, left: 40, right: 40, bottom: 60 };

  const head = [["Date", "Punch In", "Punch Out"]];
  const body = tableRecords.map((r) => [r.date, r.punchIn ?? "—", r.punchOut ?? "—"]);

  autoTable(doc, {
    head,
    body,
    startY: margin.top,
    margin: { left: margin.left, right: margin.right, bottom: margin.bottom },
    styles: {
      font: "helvetica",
      fontSize: 10,
      cellPadding: 6,
      overflow: "linebreak",
      valign: "middle",
    },
    headStyles: {
      fillColor: [245, 245, 245],
      textColor: 20,
      fontStyle: "bold",
    },
    alternateRowStyles: { fillColor: [250, 250, 250] },
    tableWidth: "auto",
    columnStyles: {
      0: { cellWidth: 120 },
      1: { cellWidth: 170 },
      2: { cellWidth: 170 },
    },
    didDrawPage: function (data) {
      const pageNumber = doc.internal.getCurrentPageInfo().pageNumber;
      drawPdfHeader(doc, pageWidth, margin, tableTitle, student);
      drawPdfFooter(doc, pageWidth, margin, pageNumber);
    },
  });

  const safe = sanitizeFilename(tableTitle || "Attendance");
  doc.save(`${safe}.pdf`);
}

/** helper to create a printable HTML string */
function buildPrintHtml(title, rowsHtml, student) {
  const now = new Date();
  const generatedAt = now.toLocaleString();
  const name = student?.name || "";
  const role = student?.role || "";

  return `<!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>${title}</title>
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <style>
          @page { margin: 36pt; }
          html, body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial; color:#111827; margin:0; padding:0; }
          .print-wrapper { padding: 14pt; box-sizing:border-box; }
          .header { margin-bottom: 8pt; border-bottom: 1px solid #e5e7eb; padding-bottom:8pt; display:flex; justify-content:space-between; align-items:center; }
          .brand { font-size: 18px; font-weight:700; letter-spacing:0.2px; }
          .meta { font-size: 10px; color:#6b7280; margin-top:4px; }
          .title { text-align:center; font-size:14px; font-weight:700; margin:10px 0 8px 0; }
          table.att-table { width:100%; border-collapse: collapse; margin-top:8px; font-size:11px; }
          table.att-table thead { background:#f8fafc; }
          table.att-table thead th { padding:10px 12px; text-align:left; border-bottom:1px solid #e6edf3; font-weight:600; }
          table.att-table tbody td { padding:10px 12px; border-bottom:1px solid #f3f6f9; vertical-align:middle; }
          table.att-table tr:nth-child(even) { background:#fbfbfb; }
          .print-footer { width:100%; display:block; margin-top:10pt; padding-top:8pt; border-top:1px solid #e5e7eb; font-size:10px; color:#6b7280; text-align:right; }
          .logo { width:56px; height:56px; object-fit:contain; border-radius:6px; background:#ffffff; display:inline-block; vertical-align:middle; margin-right:8px; }
          @media print { body { -webkit-print-color-adjust: exact; } .no-print { display:none !important; } }
        </style>
      </head>
      <body>
        <div class="print-wrapper">
          <div class="header">
            <div>
              <div style="display:flex;align-items:center;">
                
                <div>
                  <div class="brand">${escapeHtml(name)}</div>
                  <div class="meta">${escapeHtml(role)}</div>
                </div>
              </div>
            </div>
            <div style="text-align:right">
              <div class="meta">Generated: ${escapeHtml(generatedAt)}</div>
              <div class="meta">${escapeHtml(title)}</div>
            </div>
          </div>

          <div class="title">${escapeHtml(title)}</div>

          <table class="att-table" role="table" aria-label="Attendance table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Punch In</th>
                <th>Punch Out</th>
              </tr>
            </thead>
            <tbody>
              ${rowsHtml}
            </tbody>
          </table>

          <div class="print-footer">Powered by Desinerz Academy</div>
        </div>

        <script>
          // Minimal safety: ensure print is triggered after paint
          (function () {
            function tryPrint() {
              try {
                window.focus();
                window.print();
              } catch (e) {
                // swallow errors - printing may be blocked in some browsers
                console && console.warn && console.warn('Print failed', e);
              }
            }
            // give browser a bit of time to render
            if (document.readyState === 'complete') {
              setTimeout(tryPrint, 200);
            } else {
              window.addEventListener('load', function () { setTimeout(tryPrint, 200); }, false);
            }
          })();
        </script>
      </body>
    </html>`;
}

/** escape HTML to avoid injection in printed pages */
function escapeHtml(str = "") {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/**
 * Print attendance using a hidden iframe fallback.
 * This avoids needing popup permission (which window.open may require).
 *
 * tableTitle: string
 * tableRecords: [{ date, punchIn, punchOut }]
 * student: { name, role }
 */
export function printTableHtml(tableTitle = "Attendance", tableRecords = [], student = {}) {
  if (!tableRecords || tableRecords.length === 0) return;

  // build rows safely
  const rowsHtml = tableRecords
    .map(
      (r) =>
        `<tr>
          <td class="td">${escapeHtml(r.date ?? "")}</td>
          <td class="td">${escapeHtml(r.punchIn ?? "—")}</td>
          <td class="td">${escapeHtml(r.punchOut ?? "—")}</td>
        </tr>`
    )
    .join("");

  const html = buildPrintHtml(tableTitle, rowsHtml, student);

  // Attempt to open a new window first (some users prefer separate window),
  // but if blocked, fall back to an iframe to avoid popup permission prompts.
  let printTarget = null;
  try {
    printTarget = window.open("", "_blank", "width=900,height=700");
  } catch (e) {
    printTarget = null;
  }

  if (printTarget) {
    // Write to new window and let its inline script call print
    printTarget.document.open();
    printTarget.document.write(html);
    printTarget.document.close();
    // focus for some browsers
    try {
      printTarget.focus();
    } catch (e) {}
    return;
  }

  // Fallback: create a hidden iframe and print from it (no popup required)
  try {
    const iframe = document.createElement("iframe");
    iframe.style.position = "fixed";
    iframe.style.right = "0";
    iframe.style.bottom = "0";
    iframe.style.width = "0";
    iframe.style.height = "0";
    iframe.style.border = "0";
    iframe.style.visibility = "hidden";
    document.body.appendChild(iframe);

    const iframeDoc = iframe.contentWindow || iframe.contentDocument;
    const doc = iframeDoc.document || iframe.contentDocument;
    doc.open();
    doc.write(html);
    doc.close();

    // Wait for iframe to render then call print
    const tryPrint = () => {
      try {
        // for some browsers print returns a Promise, but we'll not await it
        if (iframe.contentWindow) iframe.contentWindow.focus();
        iframe.contentWindow.print();
      } catch (e) {
        console && console.warn && console.warn("iframe print failed", e);
      } finally {
        // remove iframe after a short delay to allow print dialog to spawn
        setTimeout(() => {
          try { document.body.removeChild(iframe); } catch (err) {}
        }, 800);
      }
    };

    // Some browsers need 'load' event to be fully printable
    if (iframe.contentWindow.document.readyState === "complete") {
      setTimeout(tryPrint, 250);
    } else {
      iframe.onload = () => setTimeout(tryPrint, 200);
      // safety: if onload doesn't fire, try after 600ms
      setTimeout(tryPrint, 600);
    }
  } catch (err) {
    // last fallback: write into current window (replaces current page)
    try {
      document.open();
      document.write(html);
      document.close();
      // user will need to use browser print manually
    } catch (e) {
      console && console.error && console.error("All print methods failed", e);
    }
  }
}
